---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: xps
description: turning a 2022 dell xps 13 9315 into a thin client
base-image: ghcr.io/ublue-os/base-main
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: base.yml
  - from-file: yum.yml
  - from-file: copr.yml
  - from-file: duo.yml
  - from-file: dms.yml

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - virtualbox-guest-additions
        - toolbox
        - nvtop
        - sway
        - yggdrasil
        - adcli 
        - libdnf-plugin-subscription-manager 
        - python3-subscription-manager-rhsm 
        - subscription-manager 
        - subscription-manager-rhsm-certificates 

  - from-file: fonts.yml

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - enable-linger.service
        - autologin.service
        - tailscaled.service
        - systemd-resolved.service
        - thunderbolt-net-setup.service
      disabled: []

  - type: chezmoi
    repository: "https://github.com/mecattaf/dotfiles"
    run-every: '1d'
    wait-after-boot: '15m' # longer wait after first boot to run just setup all
    disable-init: false
    disable-update: false

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: justfiles
    include:
        - setup.just

#  - type: script
#    scripts:
#        - claude-code.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        install:
          - com.google.Chrome
          - it.mijorus.gearlever
          - com.hunterwittenborn.Celeste
          - it.mijorus.collector
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - com.moonlight_stream.Moonlight

  - type: signing
